export const ATTR = 'data-dsh-vision-bench'

export const CSS = [
  'body[' + ATTR + '] .dvb-page{display:flex;flex-direction:column;gap:10px;box-sizing:border-box;padding:16px calc(var(--dsh-composer-side-clearance, 16px) + 16px) 8px;width:100%;min-width:0}',
  'body[' + ATTR + '] .dvb-title{font-weight:600;font-size:13px}',
  'body[' + ATTR + '] .dvb-hint{opacity:.58;font-size:12px;line-height:1.45}',
  'body[' + ATTR + '] .dvb-bar{display:flex;flex-wrap:wrap;gap:6px 12px;align-items:center;justify-content:space-between}',
  'body[' + ATTR + '] .dvb-health{display:flex;flex-wrap:wrap;gap:6px}',
  'body[' + ATTR + '] .dvb-chip{font-size:11px;line-height:18px;padding:0 7px;border-radius:4px;border:1px solid var(--dsw-alias-border-l2,rgba(128,128,128,.35))}',
  'body[' + ATTR + '] .dvb-chip[data-kind="ready"]{color:var(--dsw-alias-label-success,#2e7d32);border-color:currentColor}',
  'body[' + ATTR + '] .dvb-chip[data-kind="missing"]{color:var(--dsw-alias-label-danger,#c62828);border-color:currentColor}',
  'body[' + ATTR + '] .dvb-chip[data-kind="unbound"]{opacity:.7}',
  'body[' + ATTR + '] .dvb-cwd{font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;font-size:11px;opacity:.5;word-break:break-all}',
  'body[' + ATTR + '] .dvb-row{display:flex;flex-direction:column;gap:3px;min-width:0}',
  'body[' + ATTR + '] .dvb-label{display:flex;gap:8px;align-items:baseline;font-size:11px;opacity:.7}',
  'body[' + ATTR + '] .dvb-status{opacity:.7;font-size:12px}',
  'body[' + ATTR + '] .dvb-status[data-kind="ready"]{color:var(--dsw-alias-label-success,#2e7d32)}',
  'body[' + ATTR + '] .dvb-status[data-kind="missing"]{color:var(--dsw-alias-label-danger,#c62828)}',
  'body[' + ATTR + '] .dvb-input{height:28px;width:100%;box-sizing:border-box;padding:0 8px;border:1px solid var(--dsw-alias-border-l2,rgba(128,128,128,.4));border-radius:6px;background:transparent;color:inherit;font:inherit;font-size:12px;transition:border-color .15s ease}',
  'body[' + ATTR + '] .dvb-input:focus-visible{outline:none;border-color:var(--dsw-alias-label-info,#4f8ef7)}',
  'body[' + ATTR + '] .dvb-input::placeholder{opacity:.28;font-style:normal;color:inherit}',
  'body[' + ATTR + '] .dvb-input-mono{font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;font-variant-numeric:tabular-nums}',
  'body[' + ATTR + '] .dvb-combo{display:flex;gap:6px;min-width:0;align-items:center}',
  'body[' + ATTR + '] .dvb-combo .dvb-input{flex:1;min-width:0}',
  'body[' + ATTR + '] .dvb-combo .dvb-btn{flex:none}',
  'body[' + ATTR + '] .dvb-file{display:flex;gap:8px;align-items:center;min-height:28px;padding:0 4px 0 8px;border:1px solid var(--dsw-alias-border-l2,rgba(128,128,128,.4));border-radius:6px}',
  'body[' + ATTR + '] .dvb-file .dvb-btn{height:24px;padding:0 8px;border-color:transparent}',
  'body[' + ATTR + '] .dvb-actions{display:flex;flex-wrap:wrap;gap:6px;align-items:center}',
  'body[' + ATTR + '] .dvb-btn{height:28px;padding:0 10px;border:1px solid var(--dsw-alias-border-l2,rgba(128,128,128,.4));border-radius:6px;background:transparent;color:inherit;cursor:pointer;font:inherit;font-size:12px;transition:background-color .15s ease,border-color .15s ease,opacity .15s ease}',
  'body[' + ATTR + '] .dvb-btn:hover:not(:disabled){background:var(--dsw-alias-bg-layer-2,rgba(128,128,128,.1));border-color:var(--dsw-alias-border-l1,rgba(128,128,128,.55))}',
  'body[' + ATTR + '] .dvb-btn:focus-visible{outline:2px solid var(--dsw-alias-label-info,#4f8ef7);outline-offset:1px}',
  'body[' + ATTR + '] .dvb-btn-primary,.dvb-btn.is-on{font-weight:600;background:var(--dsw-alias-bg-layer-2,rgba(128,128,128,.14));border-color:var(--dsw-alias-border-l1,rgba(128,128,128,.55))}',
  'body[' + ATTR + '] .dvb-btn:disabled{opacity:.4;cursor:default}',
  'body[' + ATTR + '] .dvb-need{font-size:12px;opacity:.62}',
  'body[' + ATTR + '] .dvb-msg{font-size:12px}',
  'body[' + ATTR + '] .dvb-msg[data-kind="ok"]{color:var(--dsw-alias-label-success,#2e7d32)}',
  'body[' + ATTR + '] .dvb-msg[data-kind="err"]{color:var(--dsw-alias-label-danger,#c62828)}',
  'body[' + ATTR + '] .dvb-log{margin:0;font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;font-size:12px;line-height:1.45;white-space:pre-wrap;word-break:break-all;min-height:88px;max-height:220px;overflow:auto;padding:8px 10px;scrollbar-width:thin;overscroll-behavior:contain}',
  'body[' + ATTR + '] .dvb-path{flex:1;min-width:0;font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;font-size:12px;word-break:break-all}',
  'body[' + ATTR + '] .dvb-path[data-empty="1"]{opacity:.4}',
  'body[' + ATTR + '] .dvb-mask{position:fixed;inset:0;z-index:2147483000;display:flex;align-items:center;justify-content:center;background:rgba(0,0,0,.45)}',
  'body[' + ATTR + '] .dvb-picker{width:min(560px,92vw);max-height:70vh;overflow:auto;display:flex;flex-direction:column;gap:4px;padding:12px;border-radius:10px;background:var(--dsw-alias-bg-layer-1,#1c1c1c);color:inherit;border:1px solid var(--dsw-alias-border-l2,rgba(128,128,128,.4))}',
  'body[' + ATTR + '] .dvb-picker-head{display:flex;gap:8px;align-items:center;margin-bottom:6px}',
  'body[' + ATTR + '] .dvb-picker-head .dvb-hint{flex:1;min-width:0;word-break:break-all}',
  'body[' + ATTR + '] .dvb-picker-row{text-align:left;padding:6px 8px;border:0;border-radius:4px;background:transparent;color:inherit;font:inherit;cursor:pointer}',
  'body[' + ATTR + '] .dvb-picker-row:hover{background:rgba(128,128,128,.18)}',
  'body[' + ATTR + '] .dvb-picker-file{font-weight:600}',
  'body[' + ATTR + '] .dvb-journal{display:flex;flex-direction:column;gap:6px;padding:8px 10px;border:1px solid var(--dsw-alias-border-l2,rgba(128,128,128,.35));border-radius:6px}',
  'body[' + ATTR + '] .dvb-journal-title{font-size:11px;font-weight:600;opacity:.75;letter-spacing:.02em}',
  'body[' + ATTR + '] .dvb-task,.dvb-event{display:flex;flex-wrap:wrap;gap:6px;align-items:baseline;font-size:12px;line-height:1.45}',
  'body[' + ATTR + '] .dvb-task[data-status="error"],body[' + ATTR + '] .dvb-event[data-ok="false"]{color:var(--dsw-alias-label-danger,#c62828)}',
  'body[' + ATTR + '] .dvb-badge{font-size:11px;opacity:.7}',
  'body[' + ATTR + '] .dvb-badge[data-source="agent"]{opacity:1}',
  'body[' + ATTR + '] .dvb-panel{display:flex;flex-direction:column;gap:8px;padding:10px 12px;border:1px solid var(--dsw-alias-border-l2,rgba(128,128,128,.35));border-radius:6px;min-width:0}',
  'body[' + ATTR + '] .dvb-panel-head{display:flex;flex-wrap:wrap;gap:8px;align-items:center;min-height:28px}',
  'body[' + ATTR + '] .dvb-panel-title{font-size:12px;font-weight:600;margin-right:auto}',
  'body[' + ATTR + '] .dvb-panel-fill{min-height:0;flex:1}',
  'body[' + ATTR + '] .dvb-split{display:grid;grid-template-columns:minmax(240px,.92fr) minmax(0,1.2fr);gap:10px;align-items:stretch;width:100%;min-width:0}',
  'body[' + ATTR + '] .dvb-split>.dvb-panel{min-width:0}',
  'body[' + ATTR + '] .dvb-toolbar{display:flex;flex-wrap:wrap;gap:8px 12px;align-items:flex-end}',
  'body[' + ATTR + '] .dvb-devbar{display:flex;flex-wrap:wrap;gap:6px;align-items:center}',
  'body[' + ATTR + '] .dvb-devbar-add{display:flex;flex-wrap:wrap;gap:6px;margin-left:auto}',
  'body[' + ATTR + '] .dvb-devbar.is-empty .dvb-devbar-add{margin-left:0}',
  'body[' + ATTR + '] .dvb-toolbar .dvb-row{flex:0 1 12rem}',
  'body[' + ATTR + '] .dvb-dev{display:inline-flex;align-items:baseline;gap:6px;height:28px;padding:0 10px;border:1px solid var(--dsw-alias-border-l2,rgba(128,128,128,.4));border-radius:6px;background:transparent;color:inherit;cursor:pointer;font:inherit;font-size:12px}',
  'body[' + ATTR + '] .dvb-dev.is-on{font-weight:600;background:var(--dsw-alias-bg-layer-2,rgba(128,128,128,.14));border-color:var(--dsw-alias-border-l1,rgba(128,128,128,.55))}',
  'body[' + ATTR + '] .dvb-dev-meta{font-size:11px;opacity:.55}',
  'body[' + ATTR + '] .dvb-tag{font-size:11px;line-height:18px;padding:0 6px;border-radius:3px;border:1px solid var(--dsw-alias-border-l2,rgba(128,128,128,.35));opacity:.8}',
  'body[' + ATTR + '] .dvb-conn{display:grid;grid-template-columns:minmax(7rem,1fr) 6.5rem 5.5rem minmax(8rem,1.4fr) 6.5rem 6.5rem;gap:8px 10px}',
  'body[' + ATTR + '] .dvb-seg-add{display:grid;grid-template-columns:minmax(7rem,1.1fr) minmax(9rem,1.2fr) 6.5rem 5.5rem auto;gap:8px 10px;align-items:end}',
  'body[' + ATTR + '] .dvb-empty{opacity:.5;font-size:12px;padding:16px 2px}',
  'body[' + ATTR + '] .dvb-table-wrap{overflow:auto;border:1px solid var(--dsw-alias-border-l2,rgba(128,128,128,.28));border-radius:4px}',
  'body[' + ATTR + '] .dvb-table{width:100%;border-collapse:collapse;font-size:12px}',
  'body[' + ATTR + '] .dvb-table th{text-align:left;font-weight:500;opacity:.62;padding:5px 8px;border-bottom:1px solid var(--dsw-alias-border-l2,rgba(128,128,128,.28))}',
  'body[' + ATTR + '] .dvb-table td{padding:4px 8px;border-bottom:1px solid rgba(128,128,128,.1);vertical-align:middle}',
  'body[' + ATTR + '] .dvb-table tr[data-kind="seg"] td{background:transparent}',
  'body[' + ATTR + '] .dvb-table .dvb-val{font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;font-variant-numeric:tabular-nums}',
  'body[' + ATTR + '] .dvb-table tr[data-ok="false"] .dvb-val{color:var(--dsw-alias-label-danger,#c62828)}',
  'body[' + ATTR + '] .dvb-seg-actions{display:flex;gap:6px;justify-content:flex-end}',
  'body[' + ATTR + '] .dvb-seg-actions .dvb-btn{height:24px;padding:0 8px;font-size:12px}',
  'body[' + ATTR + '] .dvb-live{width:100%;height:100%;box-sizing:border-box;display:flex;flex-direction:column;gap:8px;padding:10px 12px}',
  'body[' + ATTR + '] .dvb-live-head{display:flex;align-items:center;justify-content:space-between;gap:8px}',
  'body[' + ATTR + '] .dvb-live-title{font-size:12px;font-weight:600}',
  'body[' + ATTR + '] .dvb-live-dot{width:8px;height:8px;border-radius:999px;background:rgba(128,128,128,.45)}',
  'body[' + ATTR + '] .dvb-live-dot[data-kind="live"]{background:var(--dsw-alias-label-success,#2e7d32)}',
  'body[' + ATTR + '] .dvb-live-dot[data-kind="err"]{background:var(--dsw-alias-label-danger,#c62828)}',
  'body[' + ATTR + '] .dvb-live-controls{display:flex;gap:6px;align-items:center}',
  'body[' + ATTR + '] .dvb-live-interval{width:72px;height:28px;padding:0 6px}',
  'body[' + ATTR + '] .dvb-live-list{overflow:auto;min-height:0;flex:1;display:flex;flex-direction:column;gap:0}',
  'body[' + ATTR + '] .dvb-live-row{display:flex;gap:8px;align-items:baseline;justify-content:space-between;font-size:12px;line-height:1.45;padding:3px 0;border-bottom:1px solid rgba(128,128,128,.1)}',
  'body[' + ATTR + '] .dvb-live-name{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;opacity:.78}',
  'body[' + ATTR + '] .dvb-live-row[data-ok="false"] .dvb-val{color:var(--dsw-alias-label-danger,#c62828)}',
  'body[' + ATTR + '] .dvb-live-close{height:24px;width:24px;padding:0;border:0;opacity:.65}',
  'body[' + ATTR + '] .dvb-btn-write{color:var(--dsw-alias-label-warning,#b45309)}',
  'body[' + ATTR + '] .dvb-btn-write.is-on,body[' + ATTR + '] .dvb-btn-write.dvb-btn-primary{font-weight:600;border-color:currentColor}',
  'body[' + ATTR + '] .dvb-write-panel{border-color:var(--dsw-alias-border-l1,rgba(128,128,128,.55))}',
  'body[' + ATTR + '] .dvb-write-inline{display:flex;flex-direction:column;gap:6px;padding:8px 10px;font-size:12px}',
  'body[' + ATTR + '] .dvb-write-head{display:flex;gap:8px;align-items:center;justify-content:space-between}',
  'body[' + ATTR + '] .dvb-write-title{font-weight:600;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}',
  'body[' + ATTR + '] .dvb-write-form{display:flex;gap:6px;align-items:center}',
  'body[' + ATTR + '] .dvb-write-form .dvb-input{flex:1;min-width:0;height:26px}',
  'body[' + ATTR + '] .dvb-write-result{font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;font-size:12px;line-height:1.5;word-break:break-all}',
  'body[' + ATTR + '] .dvb-write-result[data-kind="ok"]{color:var(--dsw-alias-label-success,#2e7d32)}',
  'body[' + ATTR + '] .dvb-write-result[data-kind="err"]{color:var(--dsw-alias-label-danger,#c62828)}',
  'body[' + ATTR + '] .dvb-write-note{display:block;font-family:inherit;opacity:.65;margin-top:2px}',
  'body[' + ATTR + '] .dvb-live-edit{height:20px;width:22px;padding:0;font-size:11px;line-height:1;flex:none;align-self:center}',
  'body[' + ATTR + '] .dvb-live-row .dvb-live-name{flex:1}',
  'body[' + ATTR + '] .dvb-bindbar{display:flex;gap:8px;align-items:center}',
  'body[' + ATTR + '] .dvb-serial-log{display:flex;flex-direction:column;max-height:260px}',
  'body[' + ATTR + '] .dvb-serial-line{white-space:pre-wrap;word-break:break-all}',
  'body[' + ATTR + '] .dvb-serial-line[data-kind="err"]{color:var(--dsw-alias-label-danger,#c62828)}',
  'body[' + ATTR + '] .dvb-serial-line[data-kind="warn"]{color:var(--dsw-alias-label-warning,#b45309)}',
  'body[' + ATTR + '] .dvb-csv-area{height:auto;padding:6px 8px;font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;font-size:11px;resize:vertical}',
  'body[' + ATTR + '] .dvb-trend-canvas{width:100%;max-width:560px;height:190px;border:1px solid var(--dsw-alias-border-l2,rgba(128,128,128,.28));border-radius:4px}',
  'body[' + ATTR + '] .dvb-trend-legend{display:flex;flex-direction:column;gap:2px}',
  'body[' + ATTR + '] .dvb-trend-row{display:flex;gap:8px;align-items:baseline;font-size:12px;line-height:1.5}',
  'body[' + ATTR + '] .dvb-trend-dot{width:8px;height:8px;border-radius:999px;flex:none;align-self:center}',
  'body[' + ATTR + '] .dvb-trend-name{min-width:0;flex:1;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;opacity:.78}',
  'body[' + ATTR + '] .dvb-frames{flex-basis:100%;font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;font-size:11px;line-height:1.5;opacity:.72;word-break:break-all}',
  'body[' + ATTR + '] .dvb-map-meta{font-size:11px;opacity:.55}',
  'body[' + ATTR + '] .dvb-map-block{display:flex;flex-direction:column;gap:3px;margin:4px 0}',
  'body[' + ATTR + '] .dvb-map-label{font-size:11px;font-weight:600;opacity:.7}',
  'body[' + ATTR + '] .dvb-map-path,.dvb-map-file{font-size:12px;line-height:1.4;padding:2px 0;display:flex;gap:8px;justify-content:space-between}',
  'body[' + ATTR + '] .dvb-map-path{font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;font-size:11px;opacity:.8}',
  'body[' + ATTR + '] .dvb-map-defs{font-size:11px;opacity:.78;line-height:1.45}',
  'body[' + ATTR + '] .dvb-map-group{margin-top:8px}',
  'body[' + ATTR + '] .dvb-map-group-name{font-size:12px;font-weight:600;padding:4px 0}',
  'body[' + ATTR + '] .dvb-map-file-name{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}',
  'body[' + ATTR + '] .dvb-map-file-mark{font-size:11px;opacity:.65;flex:none}',
  'body[' + ATTR + '] .dvb-map-funcs{font-size:11px;opacity:.62;padding:0 0 4px 8px;line-height:1.4}',
  'body[' + ATTR + '] .dvb-map-file[data-kind="missing"] .dvb-map-file-name,body[' + ATTR + '] .dvb-map-path[data-kind="missing"]{color:var(--dsw-alias-label-danger,#c62828)}',
  'body[' + ATTR + '] .dvb-map-file[data-kind="unread"] .dvb-map-file-name{opacity:.55}',
  'body[' + ATTR + '] .dvb-map-file[data-kind="out"] .dvb-map-file-name,body[' + ATTR + '] .dvb-map-path[data-kind="out"]{opacity:.6}',
  'body[' + ATTR + '] .dvb-hmi-tabs{display:flex;gap:4px;align-items:center;flex-wrap:nowrap;overflow:auto;padding:4px 0 6px;border-bottom:1px solid var(--dsw-alias-border-l2,rgba(128,128,128,.18));scrollbar-width:thin}',
  'body[' + ATTR + '] .dvb-tab{flex:none;display:inline-flex;align-items:center;gap:6px;height:28px;padding:0 10px;border:1px solid var(--dsw-alias-border-l2,rgba(128,128,128,.32));border-radius:999px;background:transparent;color:inherit;font:inherit;font-size:12px;white-space:nowrap;cursor:pointer;transition:all .15s ease}',
  'body[' + ATTR + '] .dvb-tab:hover{border-color:var(--dsw-alias-border-l1,rgba(128,128,128,.55));background:var(--dsw-alias-bg-layer-2,rgba(128,128,128,.08))}',
  'body[' + ATTR + '] .dvb-tab.is-on{font-weight:600;background:var(--dsw-alias-bg-layer-2,rgba(128,128,128,.16));border-color:var(--dsw-alias-label-info,#4f8ef7);color:var(--dsw-alias-label-info,#4f8ef7)}',
  'body[' + ATTR + '] .dvb-tab.is-warn{border-color:var(--dsw-alias-label-danger,#c62828);color:var(--dsw-alias-label-danger,#c62828)}',
  'body[' + ATTR + '] .dvb-tab-dot{width:6px;height:6px;border-radius:999px;background:var(--dsw-alias-label-success,#2e7d32);flex:none}',
  'body[' + ATTR + '] .dvb-tab-dot[data-kind="warn"]{background:var(--dsw-alias-label-warning,#b45309)}',
  'body[' + ATTR + '] .dvb-tab-dot[data-kind="idle"]{background:rgba(128,128,128,.4)}',
  'body[' + ATTR + '] .dvb-tab-badges{display:inline-flex;gap:3px;align-items:center}',
  'body[' + ATTR + '] .dvb-tab-badges .dvb-badge{min-width:14px;padding:0 4px;border-radius:999px;text-align:center;font-size:10px;line-height:14px;border:1px solid currentColor}',
  'body[' + ATTR + '] .dvb-tab-badges .dvb-badge[data-kind="err"]{color:var(--dsw-alias-label-danger,#c62828)}',
  'body[' + ATTR + '] .dvb-tab-badges .dvb-badge[data-kind="live"]{color:var(--dsw-alias-label-success,#2e7d32)}',
  'body[' + ATTR + '] .dvb-tab-badges .dvb-badge[data-kind="warn"]{color:var(--dsw-alias-label-warning,#b45309)}',
  'body[' + ATTR + '] .dvb-tab-add{width:28px;justify-content:center;padding:0;font-weight:700}',
  'body[' + ATTR + '] .dvb-tab-more{position:relative;flex:none}',
  'body[' + ATTR + '] .dvb-tab-dropdown{position:absolute;top:32px;left:0;z-index:20;display:flex;flex-direction:column;gap:4px;padding:8px;border:1px solid var(--dsw-alias-border-l2,rgba(128,128,128,.35));border-radius:8px;background:var(--dsw-alias-bg-layer-1,#1e1e1e);box-shadow:0 4px 16px rgba(0,0,0,.18);min-width:180px}',
  'body[' + ATTR + '] .dvb-vision-bar{display:flex;flex-wrap:wrap;gap:8px 12px;align-items:center;justify-content:space-between;padding:6px 10px;border:1px solid var(--dsw-alias-border-l2,rgba(128,128,128,.22));border-radius:6px;background:var(--dsw-alias-bg-layer-2,rgba(128,128,128,.06))}',
  'body[' + ATTR + '] .dvb-vision-chips{display:flex;flex-wrap:wrap;gap:6px;align-items:center}',
  'body[' + ATTR + '] .dvb-vision-meta{display:flex;gap:10px;align-items:center}',
  '@media (max-width:720px){body[' + ATTR + '] .dvb-conn,body[' + ATTR + '] .dvb-seg-add{grid-template-columns:repeat(2,minmax(0,1fr))}body[' + ATTR + '] .dvb-split{grid-template-columns:1fr}}',
].join('\n')
