/** Compatibility facade — Modbus application services live under src/application/modbus. */
export {
  ERROR_CODES,
  isStaleValue,
  pickConnPatch,
  pickModbusPatch,
  connectOp,
  pointsOp,
  createPendingWrite,
  peekPendingWrite,
  takePendingWrite,
  listPendingWrites,
  resolvePendingWrite,
  modbusRead,
  modbusWrite,
  migrateLegacyDisabled,
  modbusPoll,
  deviceAlarms,
  listFrames,
  requestFocus,
  buildEvidenceRefs,
  _internal,
} from './src/application/modbus/index.mjs'
