// @ts-check
/** Unified OpenOCD / firmware-flash error codes. */
export const FLASH_ERROR_CODES = {
  FLASH_APPROVAL_REQUIRED: 'FLASH_APPROVAL_REQUIRED',
  FLASH_APPROVAL_NOT_FOUND: 'FLASH_APPROVAL_NOT_FOUND',
  FLASH_APPROVAL_EXPIRED: 'FLASH_APPROVAL_EXPIRED',
  FLASH_APPROVAL_SCOPE_MISMATCH: 'FLASH_APPROVAL_SCOPE_MISMATCH',
  FIRMWARE_SNAPSHOT_FAILED: 'FIRMWARE_SNAPSHOT_FAILED',
  FIRMWARE_SNAPSHOT_MISMATCH: 'FIRMWARE_SNAPSHOT_MISMATCH',
  FIRMWARE_SNAPSHOT_CLEANUP_FAILED: 'FIRMWARE_SNAPSHOT_CLEANUP_FAILED',
  OPENOCD_NOT_FOUND: 'OPENOCD_NOT_FOUND',
  OPENOCD_IDENTITY_INVALID: 'OPENOCD_IDENTITY_INVALID',
  OPENOCD_PROBE_FAILED: 'OPENOCD_PROBE_FAILED',
  OPENOCD_PROBE_TIMEOUT: 'OPENOCD_PROBE_TIMEOUT',
  OPENOCD_PROBE_CANCELLED: 'OPENOCD_PROBE_CANCELLED',
  FLASH_INTERFACE_INVALID: 'FLASH_INTERFACE_INVALID',
  FLASH_TARGET_INVALID: 'FLASH_TARGET_INVALID',
  FLASH_RESULT_UNVERIFIED: 'FLASH_RESULT_UNVERIFIED',
  FLASH_TIMEOUT: 'FLASH_TIMEOUT',
  FLASH_CANCELLED: 'FLASH_CANCELLED',
  FLASH_FAILED: 'FLASH_FAILED',
}
