// @ts-check

/**
 * Keil UVSOCK official status codes (UV_STATUS) from ARM Keil UVSOCK.h.
 */
export const UV_STATUS = {
  UV_STATUS_SUCCESS: 0,
  UV_STATUS_FAILED: 1,
  UV_STATUS_NO_PROJECT: 2,
  UV_STATUS_WRITE_PROTECTED: 3,
  UV_STATUS_NO_TARGET: 4,
  UV_STATUS_NO_TOOLSET: 5,
  UV_STATUS_NOT_DEBUGGING: 6,
  UV_STATUS_ALREADY_PRESENT: 7,
  UV_STATUS_INVALID_NAME: 8,
  UV_STATUS_NOT_FOUND: 9,
  UV_STATUS_DEBUGGING: 10,
  UV_STATUS_TARGET_EXECUTING: 11,
  UV_STATUS_TARGET_STOPPED: 12,
  UV_STATUS_PARSE_ERROR: 13,
  UV_STATUS_OUT_OF_RANGE: 14,
  UV_STATUS_BP_CANCELLED: 15,
  UV_STATUS_BP_BADADDRESS: 16,
  UV_STATUS_BP_NOTSUPPORTED: 17,
  UV_STATUS_BP_FAILED: 18,
  UV_STATUS_BP_REDEFINED: 19,
  UV_STATUS_BP_DISABLED: 20,
  UV_STATUS_BP_ENABLED: 21,
  UV_STATUS_BP_CREATED: 22,
  UV_STATUS_BP_DELETED: 23,
  UV_STATUS_BP_NOTFOUND: 24,
  UV_STATUS_BUILD_OK_WARNINGS: 25,
  UV_STATUS_BUILD_FAILED: 26,
  UV_STATUS_BUILD_CANCELLED: 27,
  UV_STATUS_NOT_SUPPORTED: 28,
  UV_STATUS_TIMEOUT: 29,
  UV_STATUS_UNEXPECTED_MSG: 30,
  UV_STATUS_VERIFY_FAILED: 31,
  UV_STATUS_NO_ADRMAP: 32,
  UV_STATUS_INFO: 33,
  UV_STATUS_NO_MEM_ACCESS: 34,
  UV_STATUS_FLASH_DOWNLOAD: 35,
  UV_STATUS_BUILDING: 36,
  UV_STATUS_HARDWARE: 37,
  UV_STATUS_SIMULATOR: 38,
  UV_STATUS_BUFFER_TOO_SMALL: 39,
}

/**
 * Human-readable description for a given status code.
 * @param {number} status
 * @returns {string}
 */
export function statusToString(status) {
  for (const [key, val] of Object.entries(UV_STATUS)) {
    if (val === status) return key
  }
  return `UV_STATUS_UNKNOWN_${status}`
}
