import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')

function stripModule(src) {
  return src
    // Aliased specifiers must become REAL bindings: `X as Y` -> var Y = X.
    // Deleting import blocks outright silently kills aliases (the blank-page
    // bug of v0.17.0).
    .replace(/^import\s*\{([^}]*)\}\s*from\s*'[^']+'\n+/gm, (_m, specs) => {
      const decls = String(specs)
        .split(',')
        .map((piece) => piece.trim())
        .filter(Boolean)
        .map((spec) => {
          const mm = spec.match(/^([A-Za-z_$][\w$]*)\s+as\s+([A-Za-z_$][\w$]*)$/)
          return mm ? `var ${mm[2]} = ${mm[1]};` : null
        })
        .filter(Boolean)
      return decls.length ? decls.join('\n') + '\n' : ''
    })
    .replace(/^import\s+([A-Za-z_$][\w$]*)\s+from\s*'[^']+'\n+/gm, 'var $1 = $1;\n')
    .replace(/^import\s+\*\s+as\s+([A-Za-z_$][\w$]*)\s+from\s*'[^']+'\n+/gm, '')
    // Re-exports contribute no new factory-scope bindings: the underlying
    // symbol already exists in its defining module.
    .replace(/^export\s*\{[^}]*\}\s*from\s*'[^']+'\n+/gm, '')
    .replace(/^import[\s\S]*?from '[^']+'\n+/gm, '')
    .replace(/^export /gm, '')
}

function assertUniqueBindings(stripped, file) {
  // Split a declarator list on TOP-LEVEL commas only — commas inside arrow
  // params or object literals are not separators.
  const splitTop = (text) => {
    const out = []
    let depth = 0
    let cur = ''
    let quote = null
    for (const ch of text) {
      if (quote) {
        cur += ch
        if (ch === quote) quote = null
        continue
      }
      if (ch === "'" || ch === '"' || ch === '`') {
        quote = ch
        cur += ch
        continue
      }
      if ('([{'.includes(ch)) depth += 1
      if (')]}'.includes(ch)) depth -= 1
      if (ch === ',' && depth === 0) {
        out.push(cur)
        cur = ''
        continue
      }
      cur += ch
    }
    out.push(cur)
    return out
  }

  // Top-level declarations, including destructures and comma declarators.
  const re = /^(?:async\s+)?(?:function\*?|class)\s+([A-Za-z_$][\w$]*)|^(?:const|let|var)\s+([^;\n]+);?/gm
  let match
  while ((match = re.exec(stripped))) {
    const names = match[2]
      ? splitTop(match[2]).map((part) => {
        const decl = part.trim()
        const fnLike = decl.match(/^([A-Za-z_$][\w$]*)\s*=\s*(?:async\s*)?(?:\(|function)/)
        if (fnLike) return fnLike[1]
        const destructure = decl.match(/^(?:\{([^}]*)\}|\[([^\]]*)\])\s*=/)
        if (destructure) {
          return (destructure[1] || destructure[2])
            .split(',').map((piece) => piece.trim().split(':')[0].trim())
        }
        const simple = decl.match(/^([A-Za-z_$][\w$]*)\s*=|^([A-Za-z_$][\w$]*)$/)
        return simple ? (simple[1] || simple[2]) : []
      }).flat()
      : [match[1]]
    for (const name of names.filter(Boolean)) {
      const prev = seen.get(name)
      if (prev) {
        throw new Error('duplicate binding "' + name + '" in ' + file + ' (already in ' + prev + '); strip-concat is one factory scope')
      }
      seen.set(name, file)
    }
  }
}

const seen = new Map()

const parts = [
  'bench-i18n.mjs',
  'bench-styles.mjs',
  'bench-settings.mjs',
  'bench-points.mjs',
  'bench-devices.mjs',
  'bench-shared.mjs',
  'bench-view.mjs',
  'bench-hmi.mjs',
  'bench-live.mjs',
  'bench-map.mjs',
  'bench-overview.mjs',
  'bench-runtime.mjs',
].map((file) => {
  const stripped = stripModule(readFileSync(join(root, file), 'utf8'))
  assertUniqueBindings(stripped, file)
  return stripped
})

const banner = `// Generated by scripts/build-client.mjs. Do not edit by hand.

`
const body = `window.__ModuleLoader__.load({
  id: 'dsh-vision-bench',
  factory: (require) => {
    var module = { exports: {} }
    var exports = module.exports

    var name = 'dsh-vision-bench'
    var inject = ['slots']

${parts.join('\n')}

    exports.name = name
    exports.inject = inject
    exports.apply = apply
    return module.exports
  },
})
`

const next = banner + body
const dest = join(root, 'client.js')
const check = process.argv.includes('--check')
if (check) {
  const current = readFileSync(dest, 'utf8')
  if (current !== next) {
    console.error('client.js is stale; run node scripts/build-client.mjs')
    process.exit(1)
  }
  process.exit(0)
}
writeFileSync(dest, next)
